name: Create Issue for New Blog Post

on:
  push:
    paths:
      - "posts/*"

jobs:
  create-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create Issue
        uses: peter-evans/create-issue-from-file@v3
        with:
          title: "New Blog Post: ${{ github.event.head_commit.message }}"
          content-filepath: "posts/${{ github.event.head_commit.message }}.html"  # Adjust the file extension if necessary
          labels: "blog-post"
